### ISSUE TITLE
AS Michel I WANT TO pay to create my team on the website SO THAT my players will join the group using codes generated by the website for my team

### ISSUE THREAD

**Issue by AlexandreArmando** [Poloproduction/2P2A-COACH-E-SPORT#4]
AS Michel I WANT TO pay to create my team on the website SO THAT my players will join the group using codes generated by the website for my team

GIVEN Michel enter a team name already used by an other team
WHEN Michel wants to validate the form
THEN an error is highlighted 

GIVEN Michel enter a team name to create his group
WHEN Michel wants to validate the form
THEN the payment page appears

GIVEN Michel try not to pay for his team creation
WHEN Michel wants to validate de payment
THEN an error is highlighted

GIVEN Michel pay for his team creation
WHEN Michel wants to validate de payment
THEN a confirmation page appears and he receives a mail with registration keys

**Comment by Poloproduction** [comment]
When user is not in team / don't coach a team, he will access to 2 buttons (on account page):
- "Join a team"
- "Create my team"
